# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    # -   id: check-shebang-scripts-are-executable
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: detect-private-key
        # files: ^src/
    -   id: detect-aws-credentials
    # -   id: pretty-format-json
    # -   id: no-commit-to-branch # to not commit to main/master
        language_version: python3

# -   repo: https://github.com/PyCQA/pylint
#     rev: v2.11.1
#     hooks:
#     -   id: pylint
#         language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories=src, --py39-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: ^src/
        # args: ["--ignore-missing-imports"]
